### ISSUE TITLE
Not Compatible with iOS 11 minimum target

### ISSUE THREAD

**Issue by NaifAlrashed** [Andy1984/AORangeSlider#3]
I get this error from inside the library:
 
![screen shot 2018-11-27 at 2 37 02 pm](https://user-images.githubusercontent.com/15128710/49079577-fd417b80-f251-11e8-841a-fc3fbf7e03ee.png)

**Comment by Andy1984** [comment]
Try to not use CocoaPods and fix the error as it suggests.

**Comment by NaifAlrashed** [comment]
I will do that, but I am concerned about maintaining the library myself.

**Comment by Andy1984** [comment]
I think there is no problem with swift 4.2. Are you using swift 3?
