### ISSUE TITLE
why Low value not updating

### ISSUE THREAD

**Issue by RamohanReddy** [Andy1984/AORangeSlider#4]
Hi @alekpopek , @Andy1984 
I am not able seen low value slider updating .
I given values below code ,But its will not updating on slider.
```
videoRangeSlider.lowValue = Double(10.0)
videoRangeSlider.highValue = Double(20.0)
```

Thanks& Regards
Ramohan Reddy

**Comment by Andy1984** [comment]
If you want to set both lowValue and highValue, you can use `open func setValue(low: Double, high: Double, animated: Bool)`

You need to set minimumValue and maximumValue first. Otherwise the default range would be from 0.0 to 1.0. You can try set highValue = Double(0.5).

**Comment by RamohanReddy** [comment]
@Andy1984 
Thank u its working.
